version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: management
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "0.0.0.0:3306:3306"
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
     - mysql:mysql
    depends_on:
      - mysql
    ports:
      - "0.0.0.0:8080:8080"
